# Generated by Django 4.2.20 on 2026-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='name_es',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre (ES)'),
        ),
        migrations.AddField(
            model_name='capability',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Descripción (ES)'),
        ),
        migrations.AddField(
            model_name='capability',
            name='summary_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Resumen (ES)'),
        ),
        migrations.AddField(
            model_name='capability',
            name='title_es',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título (ES)'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='location_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación (ES)'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='name_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre (ES)'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='summary_es',
            field=models.TextField(blank=True, verbose_name='Resumen (ES)'),
        ),
        migrations.AddField(
            model_name='fundingneed',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Descripción (ES)'),
        ),
        migrations.AddField(
            model_name='fundingneed',
            name='item_es',
            field=models.CharField(blank=True, max_length=150, verbose_name='Artículo (ES)'),
        ),
        migrations.AddField(
            model_name='impactmetric',
            name='label_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etiqueta (ES)'),
        ),
        migrations.AddField(
            model_name='leadershipmember',
            name='bio_es',
            field=models.TextField(blank=True, verbose_name='Biografía (ES)'),
        ),
        migrations.AddField(
            model_name='leadershipmember',
            name='name_es',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre (ES)'),
        ),
        migrations.AddField(
            model_name='leadershipmember',
            name='role_title_es',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título del rol (ES)'),
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='body_es',
            field=models.TextField(blank=True, verbose_name='Cuerpo (ES)'),
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='summary_es',
            field=models.CharField(blank=True, max_length=300, verbose_name='Resumen (ES)'),
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título (ES)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_es',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre (ES)'),
        ),
        migrations.AddField(
            model_name='sponsorshiptier',
            name='benefits_es',
            field=models.TextField(blank=True, help_text='Spanish benefits, one per line', verbose_name='Beneficios (ES)'),
        ),
        migrations.AddField(
            model_name='sponsorshiptier',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre (ES)'),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='requirements_es',
            field=models.TextField(blank=True, help_text='Spanish requirements, one per line', verbose_name='Requisitos (ES)'),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='summary_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Resumen (ES)'),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='title_es',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título (ES)'),
        ),
        migrations.AddField(
            model_name='teamstatus',
            name='note_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota (ES)'),
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Descripción (ES)'),
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título (ES)'),
        ),
        migrations.AddField(
            model_name='trainingpipelinestage',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Descripción (ES)'),
        ),
        migrations.AddField(
            model_name='trainingpipelinestage',
            name='title_es',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título (ES)'),
        ),
    ]
