# Generated by Django 4.2.20 on 2026-09-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_affiliation_name_es_capability_description_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_es', models.CharField(blank=True, max_length=150, verbose_name='Nombre (ES)')),
                ('description', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True, verbose_name='Descripción (ES)')),
                ('order', models.PositiveIntegerField(help_text='1 = highest rank; higher numbers = lower rank')),
            ],
            options={
                'verbose_name_plural': 'Hierarchies',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='teamrole',
            name='hierarchy',
            field=models.ForeignKey(blank=True, help_text='Rank band this role belongs to (1 = highest rank).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='operations.hierarchy'),
        ),
    ]
