# Generated by Django 4.2.20 on 2026-09-02 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_hierarchy_teamrole_hierarchy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadershipMember',
        ),
    ]
