# Generated by Django 4.2.20 on 2026-09-02 20:47

import secrets
import string

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_application_codes(apps, schema_editor):
    """Assign a unique application code to any pre-existing applications."""
    VolunteerApplication = apps.get_model("operations", "VolunteerApplication")
    alphabet = string.ascii_uppercase + string.digits
    for app in VolunteerApplication.objects.filter(application_code=""):
        code = "USAR-" + "".join(secrets.choice(alphabet) for _ in range(6))
        while VolunteerApplication.objects.filter(application_code=code).exists():
            code = "USAR-" + "".join(secrets.choice(alphabet) for _ in range(6))
        app.application_code = code
        app.save(update_fields=["application_code"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0004_delete_leadershipmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='application_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(backfill_application_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='application_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for review'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='pipeline_phase',
            field=models.CharField(choices=[('application', 'Phase 1: Application submitted'), ('screening', 'Phase 2: Screening & Interview'), ('probation', 'Phase 3: Probation & Training'), ('board', 'Phase 4: Board Review'), ('active', 'Active Duty'), ('rejected', 'Rejected')], default='application', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='applications/resumes/'),
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applications/medical/')),
                ('approved', models.BooleanField(blank=True, help_text='None = not yet reviewed', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='operations.volunteerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='operations.volunteerapplication')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('certification', 'Certification'), ('medical', 'Medical')], max_length=20)),
                ('file', models.FileField(upload_to='applications/documents/')),
                ('approved', models.BooleanField(blank=True, help_text='None = not yet reviewed', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.volunteerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('application', 'Phase 1: Application submitted'), ('screening', 'Phase 2: Screening & Interview'), ('probation', 'Phase 3: Probation & Training'), ('board', 'Phase 4: Board Review'), ('active', 'Active Duty'), ('rejected', 'Rejected')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='operations.volunteerapplication')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPhaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('application', 'Phase 1: Application submitted'), ('screening', 'Phase 2: Screening & Interview'), ('probation', 'Phase 3: Probation & Training'), ('board', 'Phase 4: Board Review'), ('active', 'Active Duty'), ('rejected', 'Rejected')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.volunteerapplication')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('application', 'phase')},
            },
        ),
    ]
