# Generated by Django 4.2.20 on 2026-09-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_volunteerapplication_application_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='kind',
            field=models.CharField(choices=[('document', 'Document'), ('certification', 'Certification'), ('medical', 'Medical')], max_length=20),
        ),
    ]
