# Generated by Django 4.2.20 on 2026-09-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_applicationdocument_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpipelinestage',
            name='phase',
            field=models.CharField(blank=True, choices=[('application', 'Phase 1: Application submitted'), ('screening', 'Phase 2: Screening & Interview'), ('probation', 'Phase 3: Probation & Training'), ('board', 'Phase 4: Board Review'), ('active', 'Active Duty'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
