# Generated by Django 4.2.20 on 2026-09-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_trainingpipelinestage_phase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingPipelineStage',
        ),
    ]
