# Generated by Django 4.2.20 on 2026-09-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_delete_trainingpipelinestage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantPipelinePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_es', models.CharField(blank=True, max_length=150, verbose_name='Nombre (ES)')),
                ('description', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True, verbose_name='Descripción (ES)')),
                ('phase_number', models.PositiveIntegerField(unique=True)),
                ('pipeline_key', models.CharField(choices=[('application', 'Prerequisite and Application'), ('screening', 'Screening and Background'), ('probation', 'Physical and Practical Evaluation'), ('board', 'Board Review and Final Approval'), ('active', 'Training'), ('rejected', 'Reject')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['phase_number'],
            },
        ),
    ]
