# Generated by Django 4.2.20 on 2026-09-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_applicantpipelinephase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantpipelinephase',
            name='pipeline_key',
            field=models.CharField(choices=[('application', 'Prerequisite and Application'), ('screening', 'Screening and Background'), ('probation', 'Physical and Practical Evaluation'), ('board', 'Board Review and Final Approval'), ('active', 'Training or Rejection')], max_length=20, unique=True),
        ),
    ]
