# Generated by Django 4.2.20 on 2026-09-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_alter_applicantpipelinephase_pipeline_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='National ID number'),
        ),
    ]
