# Generated by Django 4.2.20 on 2026-09-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_volunteerapplication_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_es', models.CharField(blank=True, max_length=150, verbose_name='Nombre (ES)')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
