# Generated by Django 4.2.20 on 2026-09-05 15:46
# Manual: converts VolunteerApplication.country from a CharField holding the
# country *name* into a ForeignKey to Country, back-filling existing rows by
# matching the stored name (then the ISO code). Member gains country FK,
# id_number and blood_type; applications gain the archived flag.

from django.db import migrations, models
import django.db.models.deletion


def populate_application_country(apps, schema_editor):
    Country = apps.get_model("operations", "Country")
    VolunteerApplication = apps.get_model("operations", "VolunteerApplication")
    for app in VolunteerApplication.objects.all():
        value = (app.country_legacy or "").strip()
        if not value:
            continue
        country = Country.objects.filter(name__iexact=value).first()
        if country is None:
            country = Country.objects.filter(code__iexact=value).first()
        app.country = country
        app.save(update_fields=["country"])


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_checklist_catalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerapplication',
            old_name='country',
            new_name='country_legacy',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='operations.country', verbose_name='Country'),
        ),
        migrations.RunPython(populate_application_country, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='country_legacy',
        ),
        migrations.AddField(
            model_name='member',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Blood type'),
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='operations.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='National ID number'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='archived',
            field=models.BooleanField(default=False, help_text='Archived from the active pipeline'),
        ),
    ]