# Generated by Django 4.2.20 on 2026-09-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_application_pipeline_phase_fk_and_remove_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrole',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='teamrole',
            name='track',
        ),
    ]
