# Generated by Django 4.2.20 on 2026-09-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_remove_teamrole_slug_remove_teamrole_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamrole',
            options={'ordering': ['hierarchy__order', 'id']},
        ),
        migrations.RemoveField(
            model_name='teamrole',
            name='order',
        ),
    ]
