# Generated by opencode — manual data migration.
# Converts the four fixed choice CharFields into ForeignKeys referencing new
# bilingual lookup tables (MemberStatus, BloodType, DeploymentStatus,
# CapabilityCategory), back-filling each lookup row from the stored string.
# Also drops Capability.icon and adds Deployment.map_area (GeoJSON).

from django.db import migrations, models
import django.db.models.deletion


MEMBER_STATUSES = [
    ("active", "Active", "Activo"),
    ("probation", "Probationary", "Probatorio"),
    ("leave", "On Leave", "De Baja Temporal"),
    ("inactive", "Inactive", "Inactivo"),
]

BLOOD_TYPES = [
    ("A+", "A+", "A+"),
    ("A-", "A-", "A-"),
    ("B+", "B+", "B+"),
    ("B-", "B-", "B-"),
    ("AB+", "AB+", "AB+"),
    ("AB-", "AB-", "AB-"),
    ("O+", "O+", "O+"),
    ("O-", "O-", "O-"),
]

DEPLOYMENT_STATUSES = [
    ("active", "Active Operation", "Operación Activa"),
    ("completed", "Completed", "Completado"),
]

CAPABILITY_CATEGORIES = [
    ("heavy_technical", "Heavy/Technical Rescue", "Rescate Pesado/Técnico"),
    ("k9", "Canine (K9) Unit", "Unidad Canina (K9)"),
    ("technical_search", "Technical Search", "Búsqueda Técnica"),
    ("medical", "Medical Task Force", "Grupo Médico de Tarea"),
    ("hazmat", "Hazardous Materials & Technical Support", "Materiales Peligrosos y Soporte Técnico"),
]


def create_lookup_rows(apps, schema_editor):
    MemberStatus = apps.get_model("operations", "MemberStatus")
    BloodType = apps.get_model("operations", "BloodType")
    DeploymentStatus = apps.get_model("operations", "DeploymentStatus")
    CapabilityCategory = apps.get_model("operations", "CapabilityCategory")

    for key, note, note_es in MEMBER_STATUSES:
        MemberStatus.objects.get_or_create(status=key, defaults={"note": note, "note_es": note_es})
    for key, note, note_es in BLOOD_TYPES:
        BloodType.objects.get_or_create(status=key, defaults={"note": note, "note_es": note_es})
    for key, note, note_es in DEPLOYMENT_STATUSES:
        DeploymentStatus.objects.get_or_create(status=key, defaults={"note": note, "note_es": note_es})
    for key, note, note_es in CAPABILITY_CATEGORIES:
        CapabilityCategory.objects.get_or_create(status=key, defaults={"note": note, "note_es": note_es})


def backfill_lookups(apps, schema_editor):
    Member = apps.get_model("operations", "Member")
    Deployment = apps.get_model("operations", "Deployment")
    Capability = apps.get_model("operations", "Capability")
    MemberStatus = apps.get_model("operations", "MemberStatus")
    BloodType = apps.get_model("operations", "BloodType")
    DeploymentStatus = apps.get_model("operations", "DeploymentStatus")
    CapabilityCategory = apps.get_model("operations", "CapabilityCategory")

    statuses_by_key = {row.status: row for row in MemberStatus.objects.all()}
    blood_by_key = {row.status: row for row in BloodType.objects.all()}
    deployments_by_key = {row.status: row for row in DeploymentStatus.objects.all()}
    categories_by_key = {row.status: row for row in CapabilityCategory.objects.all()}

    for member in Member.objects.all():
        member.status = statuses_by_key.get(member.status_legacy)
        member.blood_type = blood_by_key.get(member.blood_type_legacy) if member.blood_type_legacy else None
        member.save(update_fields=["status", "blood_type"])

    for deployment in Deployment.objects.all():
        deployment.status = deployments_by_key.get(deployment.status_legacy)
        deployment.save(update_fields=["status"])

    for cap in Capability.objects.all():
        cap.category = categories_by_key.get(cap.category_legacy)
        cap.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0017_alter_teamrole_options_remove_teamrole_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=50, unique=True, verbose_name="Key")),
                ("note", models.CharField(max_length=255, blank=True)),
                ("note_es", models.CharField(max_length=255, blank=True, verbose_name="Nota (ES)")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Blood types", "ordering": ["status"]},
        ),
        migrations.CreateModel(
            name="CapabilityCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=50, unique=True, verbose_name="Key")),
                ("note", models.CharField(max_length=255, blank=True)),
                ("note_es", models.CharField(max_length=255, blank=True, verbose_name="Nota (ES)")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Capability categories", "ordering": ["status"]},
        ),
        migrations.CreateModel(
            name="DeploymentStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=50, unique=True, verbose_name="Key")),
                ("note", models.CharField(max_length=255, blank=True)),
                ("note_es", models.CharField(max_length=255, blank=True, verbose_name="Nota (ES)")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Deployment statuses", "ordering": ["status"]},
        ),
        migrations.CreateModel(
            name="MemberStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=50, unique=True, verbose_name="Key")),
                ("note", models.CharField(max_length=255, blank=True)),
                ("note_es", models.CharField(max_length=255, blank=True, verbose_name="Nota (ES)")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Member statuses", "ordering": ["status"]},
        ),
        migrations.RunPython(create_lookup_rows, migrations.RunPython.noop),
        # --- Member.status: CharField -> FK ---
        migrations.RenameField("member", "status", "status_legacy"),
        migrations.AddField(
            "member",
            "status",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="operations.memberstatus",
            ),
        ),
        # --- Member.blood_type: CharField -> FK ---
        migrations.RenameField("member", "blood_type", "blood_type_legacy"),
        migrations.AddField(
            "member",
            "blood_type",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="operations.bloodtype",
                verbose_name="Blood type",
            ),
        ),
        # --- Deployment.status: CharField -> FK ---
        migrations.RenameField("deployment", "status", "status_legacy"),
        migrations.AddField(
            "deployment",
            "status",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployments",
                to="operations.deploymentstatus",
            ),
        ),
        # --- Capability.category: CharField -> FK ---
        migrations.RenameField("capability", "category", "category_legacy"),
        migrations.AddField(
            "capability",
            "category",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capabilities",
                to="operations.capabilitycategory",
            ),
        ),
        migrations.RunPython(backfill_lookups, migrations.RunPython.noop),
        migrations.RemoveField("member", "status_legacy"),
        migrations.RemoveField("member", "blood_type_legacy"),
        migrations.RemoveField("deployment", "status_legacy"),
        migrations.RemoveField("capability", "category_legacy"),
        migrations.RemoveField("capability", "icon"),
        migrations.AddField(
            "deployment",
            "map_area",
            models.JSONField(
                blank=True,
                help_text="GeoJSON polygon of the deployment area, drawn by the admin",
                null=True,
            ),
        ),
    ]