# Generated by Django 4.2.20 on 2026-09-09 01:03

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models
import django.db.models.deletion
import re


def link_existing_members_to_users(apps, schema_editor):
    """Give every pre-existing member a login account so the member portal works.

    Usernames derive from the member email (sanitized); the password is random
    and unrecoverable — staff can reset it, or applicants get their real
    application_code / id_number credentials when activated going forward.
    """
    AuthUser = get_user_model()
    Member = apps.get_model("operations", "Member")
    dummy_password = "set-by-migration"
    for member in Member.objects.all().iterator():
        username = re.sub(r"[^A-Za-z0-9_.@+-]", "-", member.email)[:150] or f"member{member.pk}"
        user = AuthUser.objects.filter(username=username).first()
        if user is None:
            user = AuthUser.objects.create_user(
                username=username,
                email=member.email or "",
                password=dummy_password,
            )
        member.user_id = user.id
        member.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0018_lookup_tables_and_member_refactors'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Login account created when an applicant is activated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(link_existing_members_to_users, migrations.RunPython.noop),
    ]
